net: CurlHttpClient: Call `curl_easy_reset()` to fix error 'rewinding of the data'
@okman334 reported an error when using the curl HTTP client after commit
775291f5e4d ("net: Allow curl handle in CurlHttpClient to be kept alive"):

   error: curl error: Send failed since rewinding of the data stream failed.

Fix this by calling `curl_easy_reset()` before setting curl options. It
reinitializes all options previously set on a specified curl handle to
the default values while keeping the connection alive.

Closes: https://github.com/reo7sp/tgbot-cpp/issues/340
Reported-by: @okman334
Fixes: 775291f5e4debfb50174698e5cd4116779cae487 ("net: Allow curl handle in CurlHttpClient to be kept alive")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>